FROM node:22-alpine
WORKDIR /app

# Copy seluruh monorepo
COPY . .

# Install & build
RUN npm install -g pnpm
RUN pnpm install --frozen-lockfile
RUN pnpm build:packages
RUN pnpm --filter api build

WORKDIR /app/apps/api
CMD ["node", "dist/main"]